#!/bin/bash
Home=.
libDir=${Home}/lib
CP=${Home}/bin
SEP=":" 

for i in ${libDir}/*.jar ; do
    CP="${CP}${SEP}$i"
done

java -Xms128M -Xmx1000M -Xss10m -classpath $CP $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12}
